#!/usr/bin/env bash

## Description: Clean all build files and installed dependencies.

is_running() {
    ddev exec pwd &>/dev/null
}
echo "Cleaning build dependencies..."
if is_running; then
  ddev clean-build-web
  bash ./.ddev/commands/web/clean-build-web
  ddev mutagen sync
else
  bash ./.ddev/commands/web/clean-build-web
  ddev mutagen reset
fi
