#!/usr/bin/env bash

## Description: Clean all build files and installed dependencies.

is_running() {
    ddev describe 2>/dev/null | grep -qE 'web .*OK'
}
echo "Cleaning build dependencies..."
if is_running; then
  ddev clean-build-web
  bash ./.ddev/commands/web/clean-build-web
  ddev mutagen sync
else
  bash ./.ddev/commands/web/clean-build-web
  ddev mutagen reset
fi
