#!/usr/bin/env bash

## Description: Composer install

if [ -f .ddev/.plugin-dev-mode ]; then
    ddev composer config 'preferred-install.sitchco/*' source
    ddev composer config 'preferred-install.situation/*' source
    ddev composer config 'preferred-install.kadencewp/kadence-blocks' source
    ddev composer config 'preferred-install.*' dist
    trap 'ddev composer config --unset preferred-install' EXIT
fi
ddev composer install -o
