#!/usr/bin/env bash

## Description: Clean build, git hard reset/pull

ddev clean-build
mv wp-content/uploads ./ && rm -rf wp-content && mkdir -p wp-content && mv uploads wp-content/
git clean -fd
git reset --hard
git fetch
git pull
git gc
git prune
ddev mutagen reset || true