#!/bin/bash

## Description: Clean build, git hard reset/pull

/bin/bash .ddev/commands/host/clean-build
mv wp-content/uploads ./ && rm -rf wp-content && mkdir -p wp-content && mv uploads wp-content/
git add -A .
git reset --hard
git fetch
git pull
git gc
git prune
ddev mutagen reset || true