#!/bin/bash

## Description: Create the ddev local-config.php file.

cat <<EOT > ${DDEV_APPROOT}/${DDEV_DOCROOT}/local-config.php
<?php
const DB_NAME = 'db';
const DB_USER = 'db';
const DB_PASSWORD = 'db';
const DB_HOST = 'db';
const ENVIRONMENT = 'local';
const FORCE_HTTPS = true;

EOT
