#!/usr/bin/env bash

## Description: Tail the log, but only show php errors

ddev logs -f --tail 10 |
  grep --line-buffered "said into stderr:\|, referer" |
  sed -u 's/^.*into stderr: "//g' |
  sed -u 's/"$//g' |
  sed -u 's/NOTICE: PHP message: //g' |
  sed -u 's/^.*, referer/referer/g'
