#!/usr/bin/env bash

## Description: Update composer dependencies and rebuild yarn cache if needed.

# Run all upgrade migrations (kint, tabrisrp, ACF Pro, Gravity Forms, etc.)
ddev mutagen sync
ddev upgrade-migrations
ddev mutagen sync

if [ -f .github/workflows/main.yml ]; then
    if grep -q 'runner-cache' .github/workflows/main.yml; then
        sed -i '' '/runner-cache/d' .github/workflows/main.yml
    fi
fi

ddev composer update -o --no-install
ddev mutagen sync
