#!/usr/bin/env bash

## Description: Update composer dependencies and rebuild yarn cache if needed.

ddev composer config platform.php 7.4
if grep -q '"kint-php/kint": "^2.0"' composer.json; then
    ddev composer config extra.kint --unset
    ddev composer require --dev kint-php/kint:"*" --no-install
fi
if grep -q 'tabrisrp' composer.json; then
  ddev mutagen sync
  ddev ssh -- <<EOF
  jq 'del(.repositories[] | select(.url | test("tabrisrp")))' ./composer.json > ./composer.tmp && mv ./composer.tmp ./composer.json
EOF
  ddev mutagen sync
fi

if grep -q 'situation/advanced-custom-fields-pro' composer.json; then
  ddev mutagen sync
  ddev ssh -- <<EOF
  jq --indent 4 '.repositories += [{"type":"composer","url":"https://connect.advancedcustomfields.com"}]' ./composer.json > ./composer.tmp && mv ./composer.tmp ./composer.json
  composer remove situation/advanced-custom-fields-pro --no-install
  composer require wpengine/advanced-custom-fields-pro:"*" --no-install
EOF
  ddev mutagen sync
fi
ddev composer update -o --no-install
ddev mutagen sync
