#!/usr/bin/env bash

## Description: Update composer dependencies and rebuild yarn cache if needed.

ddev composer config platform.php 7.4
if grep -q '"kint-php/kint": "^2.0"' composer.json; then
    ddev composer config extra.kint --unset
    ddev composer require --dev kint-php/kint:"*" --no-install
fi
ddev composer update -o --no-install
ddev mutagen sync
