#!/usr/bin/env bash

## Description: Activate alternate build mode where the local dependencies are cleared and restored before the build.

if [ -f .ddev/.plugin-dev-mode ]; then
  rm -f .ddev/.plugin-dev-mode
  rm -f .conf/.ddev/mutagen/mutagen.yml .conf/.ddev/mutagen/.gitignore
  if [ -z "$(ls -A .conf/.ddev/mutagen)" ]; then
    rm -rf .conf/.ddev/mutagen
  fi
  if [ -z "$(ls -A .conf/.ddev)" ]; then
    rm -rf .conf/.ddev
  fi
  echo "Plugin dev mode deactivated"
else
  touch .ddev/.plugin-dev-mode
  mkdir -p .conf/.ddev/mutagen
  echo "/*" > .conf/.ddev/mutagen/.gitignore
  cat .ddev/mutagen/mutagen.yml | grep -v "node_modules\|bower" >.conf/.ddev/mutagen/mutagen.yml
  echo "Plugin dev mode activated"
fi
rm -f composer.lock
ddev clean-build
make
git add composer.lock
