#!/usr/bin/env bash

source .conf/.env
check_and_execute() {
  if [[ "$NODE_VER" == "20" ]]; then
    if ddev exec "uname -m" | grep -q "x86"; then
      ddev export-db --file=./db-backup.sql.gz
      ddev delete -Oy
      make start
      ddev import-db --file=./db-backup.sql.gz
      rm -f ./db-backup.sql.gz
    fi
  fi
}

check_and_execute