#!/usr/bin/env bash

## Description: Clean all build files and installed dependencies.

clean_directories() {
  local dirs=(
    "wp-content/vendor"
    "wp-content/plugins"
    "wp-content/mu-plugins/sitchco-core"
    "wp"
    "wp-content/themes/orchestrator"
    "wp-content/themes/sitchco-parent-theme"
    "node_modules"
  )
  for dir in "${dirs[@]}"; do
    rm -rf "$dir"
  done
}

clean_theme_directories() {
  find wp-content/themes -type d \( -name "node_modules" -o -name "bower_components" -o -name "dist" \) -prune -exec rm -rf {} +
}

clean_directories
clean_theme_directories
