#!/usr/bin/env bash
#{
  ls -al ~
  ls -al ~/.composer
  git clone git@github.com:situationinteractive/satis.git ~/satis
  mkdir -p ~/.composer
  cp ~/satis/auth.json ~/.composer/
  rm -rf ~/satis
#} >/dev/null 2>&1

