#!/usr/bin/env bash

## Description: Run the yarn/webpack/gulp build.

# currentDirectory
# buildTargets
# PLUGIN_DEV_MODE
# SITE_NAME
# SITE_TITLE
# NODE_VER

export scriptRoot=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
source "$scriptRoot/.utilities"
if [ -n "$PLUGIN_DEV_MODE" ]; then
    "$scriptRoot/toggle-build-tools" --reinforce --skip-target-install
fi

for target in "${buildTargets[@]}"; do
    targetName=$(basename $target)
    (
    cd "$target"
    if [ -n "$PLUGIN_DEV_MODE" ]; then
        find . -type d -name node_modules -prune -exec rm -rf {} \;
        pnpm install >/dev/null 2>&1
    fi
    pnpm run build | sed "s/^/[${targetName}] /"
    ) &
done
wait
