#!/usr/bin/env bash

## Description: Run lint task

# currentDirectory
# buildTargets
# PLUGIN_DEV_MODE
# SITE_NAME
# SITE_TITLE
# NODE_VER

export scriptRoot=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
source "$scriptRoot/.utilities"

for target in "${buildTargets[@]}"; do
    targetName=$(basename $target)
    (
    cd "$target"
    echo "=== ${targetName} ==="
    pnpm run lint
    echo ""
    )
done