#!/usr/bin/env bash

## Description: Build all other targets, then run VITE HMR dev in one of them.

# currentDirectory
# buildTargets
# PLUGIN_DEV_MODE
# SITE_NAME
# SITE_TITLE
# NODE_VER

export scriptRoot=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
source "$scriptRoot/.utilities"

# If there's only one target, select it automatically
if [ "${#buildTargets[@]}" -eq 1 ]; then
  selectedTarget="${buildTargets[0]}"

# Otherwise, prompt the user to choose one
else
  echo "Multiple build targets found. Please select the desired target for the HMR watch task:"
  PS3="Enter your choice [1-${#buildTargets[@]}]: "
  select selectedTarget in "${buildTargets[@]}"; do
    if [ -n "$selectedTarget" ]; then
      break
    else
      echo "Invalid selection. Try again."
    fi
  done
fi

# Build all the non-selected targets
for target in "${buildTargets[@]}"; do
  if [ "$target" != "$selectedTarget" ]; then
    targetName=$(basename "$target")
    (
      cd "$target"
      echo "=== Building ${targetName} ==="
      pnpm run build
      echo ""
    )
  fi
done

# Finally, run dev in the selected target
(
  cd "$selectedTarget"
  pnpm run dev
)
