#!/usr/bin/env bash

## Description: Install all front-end dependencies.

# currentDirectory
# buildTargets
# PLUGIN_DEV_MODE
# SITE_NAME
# SITE_TITLE
# NODE_VER

export scriptRoot=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
source "$scriptRoot/.utilities"
if [ -n "$PLUGIN_DEV_MODE" ]; then
    exit
fi

for target in "${buildTargets[@]}"; do
    targetName=$(basename $target)
    (
    cd "$target"
    echo "=== ${targetName} ==="
    find . -type d -name node_modules -prune -exec rm -rf {} \;
    pnpm install
    echo ""
    )
done