#!/bin/bash

## Description: Run a previously saved WP Sync DB migration profile.
## Usage: run-migration [args]
## Example: "ddev run-migration pull-staging"

if [ -z $1 ]; then 
  wp wpsdb migrate --help --url=${DDEV_PRIMARY_URL}
  ls .ddev/migrations | sed -e 's/\.json//' 
  exit
fi

FILE=".conf/migrations/${1}.json"

if [ -f ${FILE} ]; then
  echo "Importing Migration"
  wp option update wpsdb_settings --url=${DDEV_PRIMARY_URL} --format=json < ${FILE}
  wp plugin is-installed wp-sync-db-cli --url=${DDEV_PRIMARY_URL}
  installed=$?
  if [ $installed -eq '1' ]; then composer require wp-sync-db/wp-sync-db-cli:dev-master --dev; fi
  wp plugin is-active wp-sync-db-cli --url=${DDEV_PRIMARY_URL}
  active=$?
  if [ $active -eq '1' ]; then wp plugin activate wp-sync-db-cli --url=${DDEV_PRIMARY_URL}; fi

  echo "Running Migration..."
  migrationProfile=$(wp option get wpsdb_settings)
  isPull=$(echo "${migrationProfile}" | grep action | grep pull)
  migrationName=$(echo "${migrationProfile}" | grep name)
  echo "${migrationName}"
  wp wpsdb migrate 1 --url=${DDEV_PRIMARY_URL}
  if [ ! -z "${isPull}" ]; then
    wp plugin deactivate wp-rocket --url=${DDEV_PRIMARY_URL}
    wp plugin deactivate redis-cache --url=${DDEV_PRIMARY_URL}
    git restore --staged wp-config.php
    git restore wp-config.php
  fi
else
  echo "Migration ${1} not found."  
  echo "Delete existing migrations, set up the new one, and run ddev export-migration."
fi
