#!/usr/bin/env bash

## Description: Set up and run phpunit

if [ ! -f phpunit.xml ]; then
  echo "No phpunit.xml, exiting"
  exit
fi
mysql -uroot -proot -hdb -e "CREATE DATABASE IF NOT EXISTS db_tests; GRANT ALL ON db_tests.* TO 'db'@'%';"
if [ ! -f wp-tests-config.php ]; then
  cp ~/config/phpunit/wp-tests-config.php ./
fi
if [ ! -f local-tests-config.php ]; then
  cp ~/config/phpunit/local-tests-config.php ./
fi
jq --indent 4 '.scripts.test = "phpunit"' composer.json > composer.json.tmp && mv composer.json.tmp composer.json

composer test
