#!/usr/bin/env bash

## Description: Run WordPress CLI inside the web container
## Usage: wp [flags] [args]
## Example: "ddev wp core version" or "ddev wp plugin install user-switching --activate"
## ExecRaw: true

for arg in "$@"; do
    case "$arg" in
        --url|--url=*)
            exec wp "$@"
            ;;
    esac
done

exec wp "$@" --url="${DDEV_PRIMARY_URL}"
