#!/bin/bash
# currentDirectory
# themesDirectory
# pluginsDirectory
# childThemes
# installYarn()
# SITE_NAME
# SITE_TITLE
# NODE_VER

export scriptRoot=$(cd "${BASH_SOURCE%/*}" && pwd)
source $scriptRoot/.utilities

for buildDir in $buildDirs; do
  cd ${buildDir}
  installYarn
done

cd "${currentDirectory}"