#!/usr/bin/env bash

## Description: Install all front-end dependencies.

# currentDirectory
# themesDirectory
# pluginsDirectory
# childThemes
# installYarn()
# SITE_NAME
# SITE_TITLE
# NODE_VER

export scriptRoot=$(cd "${BASH_SOURCE%/*}" && pwd)
source $scriptRoot/.utilities

if [[ -z $SOFT_RESET ]] || [[ ! -z $DOING_UPDATE ]]; then
  for buildDir in $buildDirs; do
    cd ${buildDir}
    installYarn
  done
fi
cd "${currentDirectory}"
