#!/usr/bin/env bash

## Description: Install all front-end dependencies.

# currentDirectory
# themesDirectory
# pluginsDirectory
# childThemes
# installYarn()
# SITE_NAME
# SITE_TITLE
# NODE_VER

#export scriptRoot=$(cd "${BASH_SOURCE%/*}" && pwd)
#source $scriptRoot/.utilities
#
#for buildDir in $buildDirs; do
#  cd ${buildDir}
#  if [ -f package.json ]; then
#    yarn upgrade
#  fi
#done
#cd "${currentDirectory}"
