#!/bin/bash
# currentDirectory
# themesDirectory
# pluginsDirectory
# childThemes
# installYarn()
# SITE_NAME
# SITE_TITLE
# NODE_VER

export scriptRoot=$(cd "${BASH_SOURCE%/*}" && pwd)
source $scriptRoot/.utilities
if [ -f webpack.config.js ]; then
    installYarn
fi
for theme in $childThemes; do
  cd ${theme}
  installYarn
done

cd "${currentDirectory}"