#!/bin/bash

## Description: Run the yarn/webpack/gulp build.

# currentDirectory
# themesDirectory
# pluginsDirectory
# childThemes
# SITE_NAME
# SITE_TITLE
# NODE_VER

export scriptRoot=$(cd "${BASH_SOURCE%/*}" && pwd)
source $scriptRoot/.utilities
checkDevDependencies() {
  if [[ $(jq '.devDependencies.terser | length' package.json) = 0 ]]; then
    echo "Adding scripts..."
    yarn add --dev --exact prettier terser
  fi
}
addWebpackScripts() {
  terser='find $npm_package_theme_directory/assets/scripts -name \"*.js\" | while read fname; do terser \"$fname\" --format comments=all --output \"$fname\"; done'
  prettierJS='prettier --print-width 100 --trailing-comma none --write $npm_package_theme_directory/assets/scripts/{*.js,**/*.js}'
  prettierScss='prettier --print-width 120 --write $npm_package_theme_directory/assets/styles/'
  cleanupScss="replace '{\\\n*\\\s*}' '{}' \$npm_package_theme_directory/assets/styles/ -r --include='*.scss'"
  lint='eslint --fix --ext .js $npm_package_theme_directory/assets/scripts'
  jq --indent 4 ".scripts.terserJS = \"${terser}\" | .scripts.prettierJS = \"${prettierJS}\" | .scripts.prettierSCSS = \"${prettierScss}; ${cleanupScss}\" | .scripts.lint = \"${lint}\"" package.json >package.json.tmp && mv package.json.tmp package.json
}
addBowerScripts() {
  terser='find ./assets/scripts -name \"*.js\" | while read fname; do terser \"$fname\" --format comments=all --output \"$fname\"; done'
  prettierJS='prettier --print-width 100 --write ./assets/scripts/{*.js,**/*.js}'
  prettierScss='prettier --print-width 120 --write ./assets/styles/{*.scss,**/*.scss}'
  cleanupScss="replace '{\\\n*\\\s*}' '{}' ./assets/styles/ -r --include='*.scss'"
  jq --indent 4 ".scripts.terserJS = \"${terser}\" | .scripts.prettierJS = \"${prettierJS}\" | .scripts.prettierSCSS = \"${prettierScss}; ${cleanupScss}\"" package.json >package.json.tmp && mv package.json.tmp package.json
}

for buildDir in $buildDirs; do
  cd ${buildDir}
  if [ -f package.json ]; then
    if [ -f webpack.config.js ]; then
      checkDevDependencies
      addWebpackScripts
      yarn terserJS
      yarn prettierJS
      yarn lint
      yarn prettierSCSS
    fi
    if [ -f bower.json ]; then
      checkDevDependencies
      addBowerScripts
      yarn terserJS
      yarn prettierJS
      yarn prettierSCSS
    fi
  fi
done

cd "${currentDirectory}"
