#!/bin/bash

## Description: Run the yarn/webpack/gulp build.

# currentDirectory
# themesDirectory
# pluginsDirectory
# childThemes
# SITE_NAME
# SITE_TITLE
# NODE_VER

export scriptRoot=$(cd "${BASH_SOURCE%/*}" && pwd)
source $scriptRoot/.utilities

addLintScript() {
  if [[ $(jq '.devDependencies.prettier | length' package.json) = 0 ]]; then
    echo "Adding lint script to package.json..."
    yarn add --dev --exact prettier
    line1='eslint --fix --ext .js $npm_package_theme_directory/assets/scripts'
    line2='prettier --print-width 120 --write $npm_package_theme_directory/assets/styles/'
    line3="replace '{\\\n*\\\s*}' '{}' \$npm_package_theme_directory/assets/styles/ -r --include='*.scss'"
    jq --indent 4 ".scripts.lint |= \"${line1}; ${line2}; ${line3}\"" package.json >package.json.tmp && mv package.json.tmp package.json
  fi
}
addPrettier() {
  if [[ $(jq '.devDependencies.prettier | length' package.json) = 0 ]]; then
    echo "Adding prettier script to package.json..."
    yarn add --dev --exact prettier
    line1='prettier --print-width 120 --write ./assets/scripts/{*.js,**/*.js}'
    line2='prettier --print-width 120 --write ./assets/styles/{*.scss,**/*.scss}'
    line3="replace '{\\\n*\\\s*}' '{}' ./assets/styles/ -r --include='*.scss'"
    jq --indent 4 ".scripts.lint |= \"${line1}; ${line2}; ${line3}\"" package.json >package.json.tmp && mv package.json.tmp package.json
  fi
}

for buildDir in $buildDirs; do
  cd ${buildDir}
  if [ -f package.json ]; then
    if [ -f webpack.config.js ]; then
      addLintScript
      yarn lint
    fi
    if [ -f bower.json ]; then
      addPrettier
      yarn lint
    fi
  fi
done

cd "${currentDirectory}"
