#!/usr/bin/env bash

## Description: Clear yarn cache

# currentDirectory
# themesDirectory
# pluginsDirectory
# childThemes
# installYarn()
# SITE_NAME
# SITE_TITLE
# NODE_VER

export scriptRoot=$(cd "${BASH_SOURCE%/*}" && pwd)
source $scriptRoot/.utilities

for buildDir in $buildDirs; do
  cd ${buildDir}
  if [ -f package.json ]; then
    yarn cache clean --all
    rm -rf ./node_modules
  fi
done
cd "${currentDirectory}"
